# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec08c7bcdb5a3820bc34df9542a5603c7e15ae38e00c0e0617de898aa953232e7bb2ce045c2163c4f123fc2809174dc972f8f0fc7204b3d53cc1d9f5887a788d

test:
  secret_key_base: cbd710cf4a6a6cc7e8708be4ff743b2cacf45caecd2608e8396d7bcad1aba7daf3339bc580c675fcbeecfacdf3fc5b0a2da60d1b410cff1484cd8da9bbb07613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
