inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/test_app/**/*'
    - 'spec/*'
    - 'Gemfile'
RSpec/ScatteredSetup:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'
    - '*.gemspec'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'dri_batch_ingest.gemspec'
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Style/PredicateName:
  Exclude:
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
